### ISSUE TITLE
rank cities by 1-dimensional happiness metric.

### ISSUE THREAD

**Issue by zenglenn42** [team-jjtg/CityRank#25]

**Comment by zenglenn42** [comment]
For each city listed in this object https://github.com/zenglenn42/utbc2019-cityrank-play/blob/master/assets/js/city-metrics.js , calculate the ‘happiness’ delta between it and a value passed in (the user’s happiness preference value), such that the cities can be ranked according to how close they are to the user’s preference.

For simplicity, you can assume the user will pass in preference between 0 and 100.  The actual city happiness values range between 20 and 80.

Your method should return an array of “city, states” ordered by least delta from user preference.

**Comment by tubajack** [comment]
Have started working on this. I have created a separate repo, so that I can do my own testing without affecting the project. When I get the algorithm going, I will add my contribution to the project.
