### ISSUE TITLE
find data for city happiness

### ISSUE THREAD

**Issue by tuequach** [team-jjtg/CityRank#6]

**Comment by zenglenn42** [comment]
Jake found the following ranking of 182 cities by happiness:

https://wallethub.com/edu/happiest-places-to-live/32619/

I have statically processed that list with a script into some json, using city and state as primary key.  Initial results are [here](https://github.com/zenglenn42/utbc2019-cityrank-play/blob/master/assets/js/city-metrics.js).

**Comment by zenglenn42** [comment]
Jackson found a similar site with 100 cities more geared toward millennial preferences:

https://livability.com/best-places/top-100-best-places-to-live/2019/methodology

I'm not sure if we'll use it, but it's a nice site and I'd like to capture its location here.
