### ISSUE TITLE
find api for political affiliation

### ISSUE THREAD

**Issue by tuequach** [team-jjtg/CityRank#7]

**Comment by zenglenn42** [comment]
We can lookup red versus blue counties with [this endpoint](https://github.com/zenglenn42/utbc2019-cityrank-play/blob/master/assets/js/county-political.js).

Then we can lookup which county a city resides in with [this endpoint](https://github.com/zenglenn42/utbc2019-cityrank-play/blob/master/assets/js/city-to-county.js).

**Comment by zenglenn42** [comment]
Now we have the ability to reverse engineer this map for a given city :-)

<img width="772" alt="2016-pres-election-by-country" src="https://user-images.githubusercontent.com/21047627/56438413-7ea0b580-62a8-11e9-959f-a6d92b3e9ae0.png">

Which comes from [here](https://brilliantmaps.com/2016-county-election-map/).
